apiVersion: gitops.platform.upbound.io/v1alpha1
kind: XArgo
metadata:
  name: configuration-gitops-argocd
  annotations:
    render.crossplane.io/composition-path: apis/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  parameters:
    providerConfigName: configuration-gitops-argocd
    source:
      git:
        url: https://github.com/upbound/configuration-gitops-argocd.git
        path: gitops
        ref:
          name: HEAD
