apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    type: gitops
  name: xargo.gitops.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: gitops.platform.upbound.io/v1alpha1
    kind: XArgo
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-gitops-argocdxargo
    step: xargo
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: auto-ready
  writeConnectionSecretsToNamespace: upbound-system
